# Generated by Django 4.2.5 on 2024-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0002_jobapplication_rename_job_joblisting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
